// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case ":s3d-wrrpd;iu@7n^ivM":
            case "spaceship":return img`
..............................
........2.....................
....44..2288f.................
.f..22..2f2...................
.2f.22..222...................
.42f995444457.................
24429f2f9f29279...............
24429f2f9f29279...............
.42f995444457.................
.2f.22..222...................
.f..22..2f2...................
....44..2288f.................
........2.....................
..............................
..............................
..............................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
